# Simplified cargo-deny configuration

[graph]
all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
# Temporarily ignored advisories - tracked in GitHub issues
ignore = [
    # RUSTSEC-2025-0134: rustls-pemfile unmaintained
    # TODO: https://github.com/DominicBurkart/nanna-coder/issues/40
    "RUSTSEC-2025-0134",
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",  # ICU libraries for internationalization
]

# Some crates don't have machine readable licensing information,
# so we clarify here
[[licenses.clarify]]
name = "ollama-rs"
version = "0.2.6"
expression = "MIT"
license-files = [
    { path = "LICENSE.md", hash = 0x5a019257 },
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]